# ==============================================================================
# SCRIPT: ACS_educational_attainment_2.R
# Purpose: Generate 3-Country Skyline for Educational Attainment (BA+)
# Logic:   V2 Aggregated Income (SERIAL + INCTOT), Centralized State RPP/CPI
# Engine:  data.table for high-speed 15M+ row aggregation
# ==============================================================================
rm(list = ls()); gc()
library(ipumsr); library(dplyr); library(here); library(ggplot2); library(tibble)
library(data.table); library(scales)

# 1. SOURCE MASTER LOGIC & CUTOFFS
# ------------------------------------------------------------------------------
source(here::here("02_Scripts", "II- Shared Functions", "II-A Shared Utilities2.R"))
source(here::here("02_Scripts", "II- Shared Functions", "II-D Skyline2.R"))

cutoffs_path <- here::here("01_data", "processed", "main_tercile_cutoffs_person_inclusive2.rds")
if(!file.exists(cutoffs_path)) stop("V2 Cutoffs not found. Run II-C Border Setup V2 first.")
cutoffs <- readRDS(cutoffs_path)

# 2. CONFIGURATION & EXTRACT
# ------------------------------------------------------------------------------
USER_SAMPLE <- "us2023c" 
VARS_NEEDED <- c("SERIAL", "PERWT", "INCTOT", "STATEFIP", "AGE", "EDUC")

TARGET_DIR  <- here::here("01_data", "raw", "IPUMS_Microdata", "acs_educational_attainment")
TARGET_FILE <- file.path(TARGET_DIR, "acs_educational_attainment_aggregated.rds")

if (!file.exists(TARGET_FILE)) {
  message("--- Triggering IPUMS USA (ACS) API Extract ---")
  dir.create(TARGET_DIR, recursive = TRUE, showWarnings = FALSE)
  
  extract_def <- define_extract_micro(
    collection = "usa", 
    samples = USER_SAMPLE,
    variables = VARS_NEEDED,
    description = "Three Countries ACS Skyline - Educational Attainment (V2)"
  )
  
  submitted <- submit_extract(extract_def)
  downloadable <- wait_for_extract(submitted)
  path <- download_extract(downloadable, download_dir = TARGET_DIR)
  
  ddi <- read_ipums_ddi(path[grep("\\.xml$", path)])
  raw_data <- read_ipums_micro(ddi, verbose = FALSE)
  saveRDS(raw_data, TARGET_FILE)
} else {
  raw_data <- readRDS(TARGET_FILE)
}

# 3. CONSTRUCT TRUE HOUSEHOLD INCOME (data.table Engine)
# ------------------------------------------------------------------------------
message("Aggregating individual incomes by household...")
dt_raw <- as.data.table(raw_data)
setnames(dt_raw, toupper(names(dt_raw)))

hh_aggregated <- dt_raw[
  INCTOT != 9999999, 
  .(AGGREGATED_HHINCOME = sum(INCTOT, na.rm = TRUE)), 
  by = SERIAL
]
hh_aggregated <- as_tibble(hh_aggregated)
message("Aggregation complete.")

# 4. NORMALIZATION & RECODING
# ------------------------------------------------------------------------------
# Extract year from string (e.g., "us2023c" -> 2023)
INFLATION_ADJ <- get_inflation_multiplier(data_year = as.numeric(substring(USER_SAMPLE, 3, 6)), base_year = 2023)

prepared_data <- as_tibble(dt_raw) %>%
  left_join(hh_aggregated, by = "SERIAL") %>%
  mutate(
    PERWT = as.numeric(PERWT),
    target_indicator = if_else(as.numeric(EDUC) >= 10, 1, 0),
    
    # --- ONE-STEP REAL INCOME NORMALIZATION ---
    REAL_INCOME = AGGREGATED_HHINCOME * INFLATION_ADJ * get_state_rpp_multiplier(as.numeric(STATEFIP)),
    
    Country = case_when(
      REAL_INCOME <= cutoffs$main_cutoff1 ~ "Bottom Third",
      REAL_INCOME > cutoffs$main_cutoff1 & REAL_INCOME <= cutoffs$main_cutoff2 ~ "Middle Third",
      TRUE ~ "Top Third"
    )
  ) %>%
  filter(!is.na(PERWT), PERWT > 0, !is.na(REAL_INCOME), !is.na(Country), !is.na(target_indicator), as.numeric(AGE) >= 25)

# 5. VISUALIZATION
# ------------------------------------------------------------------------------
plot_caption <- paste0(
  "Note: Universe restricted to adults aged 25 and older.\n",
  "Income is generated by natively aggregating personal income (INCTOT) within households."
  #"Data is adjusted for inflation and spatial price parity."
)

p <- plot_economic_skyline(
  data          = prepared_data, 
  indicator_var = "target_indicator", 
  weight_var    = "PERWT", 
  y_axis_label  = "Bachelor's Degree or Higher (%)",
  plot_title    = "ACS_educational_attainment_2",
  caption_text  = plot_caption
)
print(p)