# ==============================================================================
# SCRIPT: ACS_poverty_ratio_bottom_third_2.R
# Purpose: Generate Skyline of the Income-to-Poverty Ratio (Bottom Third Only)
# Logic:   V2 Aggregated Income, Centralized State RPP/CPI, Automated Summary Stats
# ==============================================================================
rm(list = ls()); gc()
library(ipumsr); library(dplyr); library(here); library(ggplot2); library(tibble)
library(data.table); library(scales)

source(here::here("02_Scripts", "II- Shared Functions", "II-A Shared Utilities2.R"))
source(here::here("02_Scripts", "II- Shared Functions", "II-D Skyline2.R"))

cutoffs_path <- here::here("01_data", "processed", "main_tercile_cutoffs_person_inclusive2.rds")
if(!file.exists(cutoffs_path)) stop("V2 Cutoffs not found.")
cutoffs <- readRDS(cutoffs_path)

USER_SAMPLE <- "us2023c" 
VARS_NEEDED <- c("SERIAL", "PERWT", "INCTOT", "STATEFIP", "AGE", "POVERTY")
TARGET_DIR  <- here::here("01_data", "raw", "IPUMS_Microdata", "acs_poverty_ratio")
TARGET_FILE <- file.path(TARGET_DIR, "acs_poverty_ratio_aggregated.rds")

if (!file.exists(TARGET_FILE)) {
  dir.create(TARGET_DIR, recursive = TRUE, showWarnings = FALSE)
  extract_def <- define_extract_micro(collection = "usa", samples = USER_SAMPLE, variables = VARS_NEEDED)
  submitted <- submit_extract(extract_def)
  path <- download_extract(wait_for_extract(submitted), download_dir = TARGET_DIR)
  raw_data <- read_ipums_micro(read_ipums_ddi(path[grep("\\.xml$", path)]), verbose = FALSE)
  saveRDS(raw_data, TARGET_FILE)
} else {
  raw_data <- readRDS(TARGET_FILE)
}

dt_raw <- as.data.table(raw_data)
setnames(dt_raw, toupper(names(dt_raw)))

hh_aggregated <- as_tibble(dt_raw[INCTOT != 9999999, .(AGGREGATED_HHINCOME = sum(INCTOT, na.rm = TRUE)), by = SERIAL])
INFLATION_ADJ <- get_inflation_multiplier(data_year = as.numeric(substring(USER_SAMPLE, 3, 6)), base_year = 2023)

prepared_data <- as_tibble(dt_raw) %>%
  left_join(hh_aggregated, by = "SERIAL") %>%
  mutate(
    PERWT = as.numeric(PERWT),
    pov_num = as.numeric(POVERTY),
    target_indicator = pov_num / 100,
    REAL_INCOME = AGGREGATED_HHINCOME * INFLATION_ADJ * get_state_rpp_multiplier(as.numeric(STATEFIP)),
    Country = case_when(
      REAL_INCOME <= cutoffs$main_cutoff1 ~ "Bottom Third",
      REAL_INCOME > cutoffs$main_cutoff1 & REAL_INCOME <= cutoffs$main_cutoff2 ~ "Middle Third",
      TRUE ~ "Top Third"
    )
  ) %>%
  filter(!is.na(PERWT), PERWT > 0, !is.na(REAL_INCOME), 
         Country == "Bottom Third", 
         pov_num > 0, as.numeric(AGE) >= 25 & as.numeric(AGE) <= 64)

message("\n=== BOTTOM THIRD SUMMARY ===")
print(as.data.frame(get_country_summary(prepared_data, "target_indicator", "PERWT")))

plot_caption <- paste0(
  "Note: Universe restricted to adults aged 25-64 in the Bottom Third of the income distribution.\n",
  "The indicator maps the average income relative to the official Federal Poverty Line.\n",
  "Income is generated by natively aggregating personal income (INCTOT) within households."
)

p <- plot_economic_skyline(
  data          = prepared_data, 
  indicator_var = "target_indicator", 
  weight_var    = "PERWT", 
  y_axis_label  = "Income-to-Poverty Ratio (% of Federal Line)",
  plot_title    = "ACS_poverty_ratio_bottom_third_2",
  caption_text  = plot_caption
)
print(p)