# ================================================================= #
# ==== 0. ABOUT ====
# ================================================================= #
## WD location: 02_Scripts/III-Data Prep Templates/ACS
## Script: ACS_foodwater_viz.R
## Purpose: Multi-line visualization for Food Assist and High Water Burden.
## Author: Janica Murphy / Gemini
## Last Modified: 2026-01-26

# ==== 0. SETUP ====
rm(list = ls()); gc()
library(dplyr); library(ggplot2); library(grid); library(gridExtra); library(here); library(readr); library(tidyr)

source(here::here("02_Scripts", "II- Shared Functions", "II-A Shared Utilities.r"))
source(here::here("02_Scripts", "II- Shared Functions", "II-B Shared Visuals.r"))

# ================================================================= #
# ==== 1. LOAD DATA ====
# ================================================================= #
PLOT_SUBFOLDER  <- "plots"
TABLE_SUBFOLDER <- "tables"

USER_IPUMS_SAMPLE_ID <- "us2023b" # 5-year sample
USER_INDICATOR_NAME  <- "Food_Water_Security"
USER_WEIGHT_VARIABLE <- "PERWT"

OUTPUT_PLOT_NAME  <- "plot_foodwater.png"
OUTPUT_TABLE_NAME <- "table_foodwater.png"

# Load prepared data (generated by the companion _prepare.R script)
PREPARED_DATA_FILE <- here::here("01_data", "processed", "IPUMS_Microdata", 
                                 "prepared_ACS_Food_Water_Security.rds")

prepared_data <- readRDS(PREPARED_DATA_FILE)
main_cutoffs  <- readRDS(here::here("01_data", "processed", "main_tercile_cutoffs.rds"))
borders_df    <- readr::read_csv(here::here("01_data", "processed", "within_tercile_quantile_borders.csv"), show_col_types = FALSE)

# Assign households to income groups
data_with_groups <- assign_income_groups(
  data_to_process = prepared_data,
  borders_df      = borders_df,
  income_var_name = "HHINCOME_CLEAN",
  detail_level    = "Groups_20",
  main_cutoff1    = main_cutoffs$main_cutoff1,
  main_cutoff2    = main_cutoffs$main_cutoff2
) %>% filter(!is.na(income_tercile))

# ================================================================= #
# ==== 2. DATA SUMMARIZATION ====
# ================================================================= #

# 2.1. U.S. Population Baseline
total_population <- data_with_groups %>%
  summarise(
    Country = paste("ACS", gsub("us", "20", USER_IPUMS_SAMPLE_ID), "5-Year"),
    n = n(),
    "Water Burden" = weighted.mean(ind_water_high_burden, w = .data[[USER_WEIGHT_VARIABLE]], na.rm = TRUE),
    "Food Stamps"  = weighted.mean(ind_snap, w = .data[[USER_WEIGHT_VARIABLE]], na.rm = TRUE),
    "Pub. Assist"  = weighted.mean(ind_pap, w = .data[[USER_WEIGHT_VARIABLE]], na.rm = TRUE)
  )

# 2.2. Country Summaries (By Tercile)
country_summary <- data_with_groups %>%
  group_by(income_tercile) %>%
  summarise(
    n = n(),
    "Water Burden" = weighted.mean(ind_water_high_burden, w = .data[[USER_WEIGHT_VARIABLE]], na.rm = TRUE),
    "Food Stamps"  = weighted.mean(ind_snap, w = .data[[USER_WEIGHT_VARIABLE]], na.rm = TRUE),
    "Pub. Assist"  = weighted.mean(ind_pap, w = .data[[USER_WEIGHT_VARIABLE]], na.rm = TRUE),
    .groups = "drop"
  ) %>%
  mutate(Country = case_when(
    income_tercile == "Tercile 1 (Bottom)" ~ "Bottom Country",
    income_tercile == "Tercile 2 (Middle)" ~ "Middle Country",
    income_tercile == "Tercile 3 (Top)"    ~ "Top Country"
  )) %>%
  select(Country, n, "Water Burden", "Food Stamps", "Pub. Assist")

# 2.3. Formatting for tableGrob (Standardizing output format)
table_data_final <- bind_rows(total_population, country_summary) %>%
  mutate(across(where(is.numeric) & !n, ~sprintf("%.2f%%", . * 100))) %>%
  mutate(n = scales::comma(n))

colnames(table_data_final) <- c(
  "bold('Country')", 
  "bold(italic('n'))", 
  "bold('Water Burden')", 
  "bold('SNAP Recipient')",
  "bold('Public Assistance')"
)

# ================================================================= #
# ==== 3. GENERATE TREND PLOT ====
# ================================================================= #
summary_plotting <- data_with_groups %>%
  group_by(income_tercile, fine_income_group) %>%
  summarise(
    "High Water Burden" = weighted.mean(ind_water_high_burden, w = .data[[USER_WEIGHT_VARIABLE]], na.rm = TRUE),
    "Food Stamps"       = weighted.mean(ind_snap, w = .data[[USER_WEIGHT_VARIABLE]], na.rm = TRUE),
    "Public Assistance" = weighted.mean(ind_pap, w = .data[[USER_WEIGHT_VARIABLE]], na.rm = TRUE),
    .groups = "drop"
  )

final_plot <- create_multi_line_plot(
  summary_data     = summary_plotting,
  y_vars           = c("High Water Burden", "Food Stamps", "Public Assistance"),
  y_labels         = c("High Water Burden (>=1% Income)", "Food Stamps (SNAP)", "Public Assistance"),
  plot_title       = "Food and Water Security",
  y_axis_label     = "Weighted Percentage of Population",
  y_axis_format    = "percent",
  output_filename  = paste0("../", PLOT_SUBFOLDER, "/", OUTPUT_PLOT_NAME),
  fine_group_level = "Groups_20",
  border_t1_t2     = main_cutoffs$main_cutoff1,
  border_t2_t3     = main_cutoffs$main_cutoff2
)

grid.newpage(); grid.draw(final_plot)

# ================================================================= #
# ==== 4. EXPORT SUMMARY TABLE ====
# ================================================================= #
rows_n <- nrow(table_data_final)
cols_n <- ncol(table_data_final)

# 1. Define Horizontal Alignment Vectors
# Col 1 (Country) is left-aligned (0); others are center-aligned (0.5)
header_hjust <- c(0, 0.5, 0.5, 0.5, 0.5)
header_x     <- c(0.02, 0.5, 0.5, 0.5, 0.5)

# 2. Define Font Face Matrix (Bold for the first row of data)
adj_fontface <- matrix("plain", nrow = rows_n, ncol = cols_n)
adj_fontface[1, ] <- "bold"

# 3. Create the Theme with strict Vertical and Horizontal Anchors
my_table_theme <- ttheme_minimal(
  base_family = "serif",
  core = list(
    fg_params = list(
      fontface = adj_fontface, 
      hjust    = matrix(rep(header_hjust, each = rows_n), nrow = rows_n), 
      x        = matrix(rep(header_x, each = rows_n), nrow = rows_n), 
      vjust    = 0.5, # Vertical center
      fontsize = 10
    )
  ),
  colhead = list(
    fg_params = list(
      fontsize = 11, 
      parse    = TRUE, # For bold() expressions
      hjust    = header_hjust, 
      x        = header_x,
      vjust    = 0.5,  # Vertical baseline alignment
      y        = 0.5   # Forced vertical anchor point
    )
  )
)

# Create the table object
table_grob <- tableGrob(table_data_final, rows = NULL, theme = my_table_theme)

# Formatted Notes Section
notes_vbox <- grobTree(
  textGrob("Notes:", gp = gpar(fontface = "bold", fontsize = 8.5, family = "serif"), hjust = 0, x = 0.05, y = 0.90),
  textGrob(paste0("1. Data: IPUMS ACS 2019-2023"), 
           gp = gpar(fontface = "italic", fontsize = 8, family = "serif"), hjust = 0, x = 0.05, y = 0.75),
  textGrob("2. Interpretation: Percentages reflect the share of individuals living in households facing each condition.", 
           gp = gpar(fontface = "italic", fontsize = 8, family = "serif"), hjust = 0, x = 0.05, y = 0.60),
  textGrob("3. Variables Utilized: FOODSTMP (SNAP), INCWELFR (Public Assistance), and Ratio of COSTWATR to HHINCOME.", 
           gp = gpar(fontface = "italic", fontsize = 8, family = "serif"), hjust = 0, x = 0.05, y = 0.45)
)

# Combine Table and Notes
final_layout <- grid.arrange(table_grob, notes_vbox, heights = unit.c(unit(1, "null"), unit(8, "lines")))

# Save visual
png(here::here("03_output", TABLE_SUBFOLDER, OUTPUT_TABLE_NAME), width = 950, height = 550, res = 120)
grid.draw(final_layout)
dev.off()

message("SUCCESS: Column headers vertically aligned and visual exported.")